<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'

import {
  createBugReport,
  getBugReportDetail,
  submitBugReport,
  updateBugReport,
} from '@/api/bugreport'
import { getTicketDetail, getTicketPage } from '@/api/ticket'
import { getUserList } from '@/api/user'
import type {
  BugReportCreateInput,
  BugReportDetailOutput,
  BugReportRelatedTicketOutput,
  BugReportUpdateInput,
  DefectCategoryOutput,
} from '@/types/bugreport'
import type { TicketListOutput } from '@/types/ticket'
import type { UserListOutput } from '@/types/user'
import { notifySuccess, notifyWarning } from '@/utils/feedback'
import { getCachedDefectCategoryDict } from '@/utils/bugreport-dict-cache'
import { getBugReportStatusLabel, getBugReportStatusTagType, isBugReportEditable } from '@/utils/bugreport'
import BugReportInstructionContent from '@/views/bugreport/BugReportInstructionContent.vue'
import { BUGREPORT_LOGIC_CAUSE_OPTIONS } from '@/constants/bugreport-logic-cause'

interface TicketOption {
  value: number
  label: string
}

const route = useRoute()
const router = useRouter()

const loading = ref(false)
const submitLoading = ref(false)
const users = ref<UserListOutput[]>([])
const defectCategories = ref<DefectCategoryOutput[]>([])
const ticketOptions = ref<TicketOption[]>([])
const ticketLoading = ref(false)
const prefillLoading = ref(false)
const currentStatus = ref('DRAFT')

// Mobile preview modal
const showMobilePreview = ref(false)

/** 窄屏下采用纵向表单与精简工具栏，避免底部被裁切、严重级别长说明占满一屏 */
const MOBILE_EDIT_BREAKPOINT = 768
/** 平板及以下不展示侧栏长说明，改为抽屉，避免表单+说明超长一页 */
const INSTRUCTION_DRAWER_BREAKPOINT = 991
const isMobileNarrow = ref(false)
const useInstructionDrawer = ref(false)
const showInstructionDrawer = ref(false)
/** 折叠面板展开项 name，空数组表示默认收起「更多字段」 */
const advancedCollapseActive = ref<string[]>([])
const showSeverityDescriptions = ref(false)

function updateMobileEditLayout(): void {
  if (typeof window === 'undefined') {
    return
  }
  const w = window.innerWidth
  isMobileNarrow.value = w <= MOBILE_EDIT_BREAKPOINT
  useInstructionDrawer.value = w <= INSTRUCTION_DRAWER_BREAKPOINT
}

let ticketSearchTimer: ReturnType<typeof setTimeout> | null = null
let ticketSearchToken = 0
let skipAutoFill = false

const lastAutoGenerated = {
  problemDesc: '',
  impactScope: '',
  solution: '',
  severityLevel: 'P2',
}

const SEVERITY_LEVELS = [
  {
    value: 'P0',
    label: 'P0（致命）',
    desc: '核心功能完全不能使用，影响大量商户，阻碍正常业务操作；财务等关键数据丢失无法追回；造成数据损坏泄露。',
  },
  {
    value: 'P1',
    label: 'P1（重大）',
    desc: '核心业务部分不能使用，影响较多用户正常业务开展；数据异常但可追回；出现设计未预料的严重异常。',
  },
  {
    value: 'P2',
    label: 'P2（严重）',
    desc: '重要功能异常但有临时替代方案；中等范围用户受影响；有一定经济损失风险。',
  },
  {
    value: 'P3',
    label: 'P3（一般）',
    desc: '非核心业务部分不能使用；条件触发的偶发错误；无直接经济损失但影响用户体验。',
  },
  {
    value: 'P4',
    label: 'P4（轻微）',
    desc: '轻微影响非核心业务或功能；概率性影响用户体验，如文案排版、错别字等视觉问题。',
  },
]

const form = reactive({
  problemDesc: '',
  logicCausePath: [] as string[],
  logicCauseDetail: '',
  defectCategory: '',
  introducedProject: '',
  startDate: '' as string,
  resolveDate: '' as string,
  tempResolveDate: '' as string,
  solution: '',
  tempSolution: '',
  impactScope: '',
  severityLevel: 'P2',
  reporterId: undefined as number | undefined,
  reviewerId: undefined as number | undefined,
  remark: '',
  ticketIds: [] as number[],
  responsibleUserIds: [] as number[],
  autoPrefill: true,
})

const reportId = computed(() => {
  const value = Number(route.params.id)
  return Number.isFinite(value) && value > 0 ? value : 0
})

const isEditMode = computed(() => Boolean(reportId.value))
const canEdit = computed(() => !isEditMode.value || isBugReportEditable(currentStatus.value))


const logicCauseOptions = computed(() => BUGREPORT_LOGIC_CAUSE_OPTIONS)
const selectedLogicCause = computed<string | undefined>({
  get: () => form.logicCausePath[0],
  set: (value) => {
    form.logicCausePath = value ? [value] : []
  },
})

// Copy content
const copyContent = computed(() => {
  const lines: string[] = []
  lines.push(`问题描述：${form.problemDesc || '-'}`)
  if (form.logicCausePath[0]) {
    lines.push(`逻辑归因：${form.logicCausePath[0]}`)
  }
  if (form.logicCauseDetail) {
    lines.push(`归因明细：${form.logicCauseDetail}`)
  }
  lines.push(`缺陷分类：${form.defectCategory || '-'}`)
  if (form.introducedProject) {
    lines.push(`引入项目：${form.introducedProject}`)
  }
  if (form.startDate) {
    lines.push(`开始时间：${form.startDate}`)
  }
  lines.push(`严重级别：${form.severityLevel || '-'}`)
  if (form.impactScope) {
    lines.push(`影响范围：${form.impactScope}`)
  }
  if (form.tempResolveDate) {
    lines.push(`临时解决时间：${form.tempResolveDate}`)
  }
  if (form.tempSolution) {
    lines.push(`临时解决方案：${form.tempSolution}`)
  }
  if (form.resolveDate) {
    lines.push(`彻底解决时间：${form.resolveDate}`)
  }
  if (form.solution) {
    lines.push(`彻底解决方案：${form.solution}`)
  }
  if (form.remark) {
    lines.push(`备注：${form.remark}`)
  }
  return lines.join('\n')
})

function buildTicketLabel(ticketNo?: string, title?: string): string {
  if (ticketNo && title) {
    return `${ticketNo} - ${title}`
  }
  if (ticketNo) {
    return ticketNo
  }
  if (title) {
    return title
  }
  return '-'
}

function mergeTicketOptionsByDetail(items?: BugReportRelatedTicketOutput[]): void {
  if (!items?.length) {
    return
  }
  const optionMap = new Map<number, TicketOption>()
  ticketOptions.value.forEach((item) => optionMap.set(item.value, item))
  items.forEach((item) => {
    if (!item.ticketId) {
      return
    }
    optionMap.set(item.ticketId, {
      value: item.ticketId,
      label: buildTicketLabel(item.ticketNo, item.title),
    })
  })
  ticketOptions.value = Array.from(optionMap.values())
}

function mergeTicketOptionsBySearch(items?: TicketListOutput[]): void {
  if (!items?.length) {
    return
  }
  const optionMap = new Map<number, TicketOption>()
  ticketOptions.value.forEach((item) => optionMap.set(item.value, item))
  items.forEach((item) => {
    optionMap.set(item.id, {
      value: item.id,
      label: buildTicketLabel(item.ticketNo, item.title),
    })
  })
  ticketOptions.value = Array.from(optionMap.values())
}

function toDateOnlyText(input?: string): string {
  if (!input) {
    return ''
  }
  return input.length >= 10 ? input.slice(0, 10) : input
}

function fillFormByDetail(detail: BugReportDetailOutput): void {
  skipAutoFill = true
  form.problemDesc = detail.problemDesc || ''
  form.logicCausePath = detail.logicCauseLevel1 ? [detail.logicCauseLevel1] : []
  form.logicCauseDetail = detail.logicCauseDetail || ''
  form.defectCategory = detail.defectCategory || ''
  form.introducedProject = detail.introducedProject || ''
  form.startDate = toDateOnlyText(detail.startDate)
  form.resolveDate = toDateOnlyText(detail.resolveDate)
  form.tempResolveDate = toDateOnlyText(detail.tempResolveDate)
  form.solution = detail.solution || ''
  form.tempSolution = detail.tempSolution || ''
  form.impactScope = detail.impactScope || ''
  form.severityLevel = detail.severityLevel || 'P2'
  form.reporterId = detail.reporterId
  form.reviewerId = detail.reviewerId
  form.remark = detail.remark || ''
  form.ticketIds = detail.tickets?.map((item) => item.ticketId) || []
  form.responsibleUserIds = detail.responsibleUsers?.map((item) => item.userId) || []
  form.autoPrefill = false
  currentStatus.value = detail.status || 'DRAFT'
  mergeTicketOptionsByDetail(detail.tickets)
  lastAutoGenerated.problemDesc = form.problemDesc
  lastAutoGenerated.impactScope = form.impactScope
  lastAutoGenerated.solution = form.solution
  lastAutoGenerated.severityLevel = form.severityLevel
  setTimeout(() => {
    skipAutoFill = false
  }, 0)
}

async function loadBaseData(): Promise<void> {
  const [userList, categoryList] = await Promise.all([
    getUserList({}),
    getCachedDefectCategoryDict(),
  ])
  users.value = userList || []
  defectCategories.value = categoryList || []
}

async function loadDetail(): Promise<void> {
  if (!reportId.value) {
    return
  }
  loading.value = true
  try {
    const detail = await getBugReportDetail(reportId.value)
    fillFormByDetail(detail)
    if (!isBugReportEditable(detail.status)) {
      notifyWarning('当前简报状态不可编辑，仅可查看详情')
    }
  } finally {
    loading.value = false
  }
}

async function searchTickets(keyword: string): Promise<void> {
  const currentToken = ++ticketSearchToken
  ticketLoading.value = true
  try {
    const normalized = keyword.trim()
    const result = await getTicketPage({
      pageNum: 1,
      pageSize: 20,
      view: 'all',
      ticketNo: normalized || undefined,
      title: normalized || undefined,
    })
    if (currentToken !== ticketSearchToken) {
      return
    }
    mergeTicketOptionsBySearch(result.records || [])
  } finally {
    if (currentToken === ticketSearchToken) {
      ticketLoading.value = false
    }
  }
}

function handleTicketRemoteSearch(keyword: string): void {
  if (ticketSearchTimer) {
    clearTimeout(ticketSearchTimer)
  }
  ticketSearchTimer = setTimeout(() => {
    void searchTickets(keyword)
  }, 260)
}

function normalizeStepsToOneLine(raw: string): string {
  const lines = raw
    .split(/\n/)
    .map((line) => line.replace(/^\s*\d+\s*[.、)）]\s*/, '').trim())
    .filter(Boolean)
  const joined = lines.join(' → ')
  return joined.length > 120 ? joined.slice(0, 117) + '…' : joined
}

function trimTrailingPunct(text: string): string {
  return text.replace(/[，。！？,.!?\s]+$/, '').trim()
}

type TicketSummarySource = {
  ticketNo?: string
  title?: string
  description?: string
  bugCustomerInfo?: { problemDesc?: string; expectedResult?: string } | null
  bugTestInfo?: { actualResult?: string; reproduceSteps?: string } | null
}

function buildProblemDescSummary(tickets: TicketSummarySource[]): string {
  const valid = tickets.filter(
    (t) => t.title || t.description || t.bugCustomerInfo?.problemDesc || t.bugTestInfo?.actualResult,
  )
  if (valid.length === 0) return ''

  const sections: string[] = []

  if (valid.length > 1) {
    const nos = valid
      .map((t) => t.ticketNo)
      .filter(Boolean)
      .join('、')
    sections.push(`本次简报共关联 ${valid.length} 个工单${nos ? `（${nos}）` : ''}，问题概述如下：`)
  }

  valid.forEach((ticket, idx) => {
    const ref = [ticket.ticketNo, ticket.title].filter(Boolean).join(' ')
    const sentences: string[] = []

    const problem = trimTrailingPunct(ticket.bugCustomerInfo?.problemDesc || ticket.description || '')
    if (problem) {
      sentences.push(problem)
    }

    const actual = trimTrailingPunct(ticket.bugTestInfo?.actualResult || '')
    const expected = trimTrailingPunct(ticket.bugCustomerInfo?.expectedResult || '')
    if (actual && expected) {
      sentences.push(`实际${actual}，与预期（${expected}）不符`)
    } else if (actual && !problem.includes(actual.slice(0, 12))) {
      sentences.push(`实际现象为${actual}`)
    }

    const rawSteps = (ticket.bugTestInfo?.reproduceSteps || '').trim()
    if (rawSteps) {
      const stepsLine = normalizeStepsToOneLine(rawSteps)
      if (stepsLine) {
        sentences.push(`复现路径：${stepsLine}`)
      }
    }

    if (sentences.length === 0) {
      if (ref) sentences.push(`相关工单：${ref}`)
      else return
    }

    let para = sentences.join('，') + '。'
    para = para.replace(/[，。！？]+([，。！？])/g, '$1')

    if (valid.length > 1) {
      sections.push(`${idx + 1}. 【${ref}】${para}`)
    } else {
      sections.push(para)
    }
  })

  return sections.join('\n').slice(0, 1000)
}

const SEVERITY_ORDER: Record<string, number> = { P0: 0, P1: 1, P2: 2, P3: 3 }

function pickHighestSeverity(levels: (string | undefined | null)[]): string {
  let best = 'P2'
  let bestRank: number = SEVERITY_ORDER['P2'] ?? 2
  for (const level of levels) {
    if (!level) continue
    const rank = SEVERITY_ORDER[level]
    if (rank !== undefined && rank < bestRank) {
      best = level
      bestRank = rank
    }
  }
  return best
}

async function autoFillFromTickets(ticketIds: number[]): Promise<void> {
  if (ticketIds.length === 0) return
  prefillLoading.value = true
  try {
    const details = await Promise.all(ticketIds.map((id) => getTicketDetail(id)))

    const newProblemDesc = buildProblemDescSummary(details)
    if (form.problemDesc === lastAutoGenerated.problemDesc) {
      form.problemDesc = newProblemDesc
      lastAutoGenerated.problemDesc = newProblemDesc
    }

    const firstTicket = details[0]
    if (firstTicket) {
      const newSeverity = pickHighestSeverity(details.map((d) => d.bugTestInfo?.severityLevel))
      if (form.severityLevel === lastAutoGenerated.severityLevel) {
        form.severityLevel = newSeverity
        lastAutoGenerated.severityLevel = newSeverity
      }

      const newImpact = details
        .map((d) => d.bugTestInfo?.impactScope || '')
        .filter(Boolean)
        .join('；')
        .slice(0, 500)
      if (newImpact && form.impactScope === lastAutoGenerated.impactScope) {
        form.impactScope = newImpact
        lastAutoGenerated.impactScope = newImpact
      }

      const newSolution = (firstTicket.bugDevInfo?.fixSolution || '').slice(0, 1000)
      if (newSolution && form.solution === lastAutoGenerated.solution) {
        form.solution = newSolution
        lastAutoGenerated.solution = newSolution
      }
    }
  } finally {
    prefillLoading.value = false
  }
}

watch(
  () => form.ticketIds.slice(),
  async (newIds, oldIds) => {
    if (skipAutoFill) return
    if (!canEdit.value) return
    const addedIds = newIds.filter((id) => !oldIds?.includes(id))
    if (addedIds.length === 0) return
    await autoFillFromTickets(newIds)
  },
)

function validateBeforeSave(): boolean {
  if (!form.problemDesc.trim()) {
    notifyWarning('请填写问题描述')
    return false
  }
  if (!form.defectCategory) {
    notifyWarning('请选择缺陷分类')
    return false
  }
  if (form.ticketIds.length === 0) {
    notifyWarning('请至少关联一个工单')
    return false
  }
  if (form.startDate && form.resolveDate && form.startDate > form.resolveDate) {
    notifyWarning('开始日期不能晚于解决日期')
    return false
  }
  return true
}

function buildPayload():
  | BugReportCreateInput
  | BugReportUpdateInput {
  const selectedLogicCause = form.logicCausePath[0] || undefined
  return {
    problemDesc: form.problemDesc.trim(),
    // 逻辑归因改为12类单选，所以只写一级，二级留空以保持接口兼容。
    logicCauseLevel1: selectedLogicCause,
    logicCauseLevel2: undefined,
    logicCauseDetail: form.logicCauseDetail.trim() || undefined,
    defectCategory: form.defectCategory || undefined,
    introducedProject: form.introducedProject.trim() || undefined,
    startDate: form.startDate || undefined,
    resolveDate: form.resolveDate || undefined,
    tempResolveDate: form.tempResolveDate || undefined,
    solution: form.solution.trim() || undefined,
    tempSolution: form.tempSolution.trim() || undefined,
    impactScope: form.impactScope.trim() || undefined,
    severityLevel: form.severityLevel || undefined,
    reporterId: form.reporterId,
    reviewerId: form.reviewerId,
    remark: form.remark.trim() || undefined,
    ticketIds: [...form.ticketIds],
    responsibleUserIds: [...form.responsibleUserIds],
    autoPrefill: form.autoPrefill,
  }
}

async function handleSaveDraft(): Promise<void> {
  if (!canEdit.value) {
    notifyWarning('当前状态不可编辑')
    return
  }
  const valid = validateBeforeSave()
  if (!valid) {
    return
  }
  submitLoading.value = true
  try {
    const payload = buildPayload()
    if (reportId.value) {
      await updateBugReport(reportId.value, payload as BugReportUpdateInput)
      notifySuccess('简报草稿保存成功')
    } else {
      const newId = await createBugReport(payload as BugReportCreateInput)
      notifySuccess('简报草稿创建成功')
      await router.replace(`/bug-report/edit/${newId}`)
    }
  } finally {
    submitLoading.value = false
  }
}

async function handleSaveAndSubmit(): Promise<void> {
  if (!canEdit.value) {
    notifyWarning('当前状态不可编辑')
    return
  }
  const valid = validateBeforeSave()
  if (!valid) {
    return
  }
  if (!form.reviewerId) {
    notifyWarning('提交审核前请先选择审核人')
    return
  }
  submitLoading.value = true
  try {
    const payload = buildPayload()
    let targetId = reportId.value
    if (targetId) {
      await updateBugReport(targetId, payload as BugReportUpdateInput)
    } else {
      targetId = await createBugReport(payload as BugReportCreateInput)
    }
    await submitBugReport(targetId, {
      reviewerId: form.reviewerId,
    })
    notifySuccess('简报提交审核成功')
    await router.push(`/bug-report/detail/${targetId}`)
  } finally {
    submitLoading.value = false
  }
}

function handleCancel(): void {
  if (reportId.value) {
    router.push(`/bug-report/detail/${reportId.value}`)
    return
  }
  router.push('/bug-report')
}

async function handleCopyContent(): Promise<void> {
  try {
    await navigator.clipboard.writeText(copyContent.value)
    notifySuccess('已复制到剪贴板')
  } catch {
    notifyWarning('复制失败，请手动复制')
  }
}

function handleMobileToolbarCommand(command: string): void {
  if (command === 'preview') {
    showMobilePreview.value = true
    return
  }
  if (command === 'copy') {
    void handleCopyContent()
  }
}

onMounted(async () => {
  updateMobileEditLayout()
  window.addEventListener('resize', updateMobileEditLayout)
  await loadBaseData()
  await searchTickets('')
  if (reportId.value) {
    await loadDetail()
  }
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', updateMobileEditLayout)
})

watch(
  () => reportId.value,
  async (value, oldValue) => {
    if (!value || value === oldValue) {
      return
    }
    await loadDetail()
  },
)

watch(useInstructionDrawer, (drawer) => {
  if (!drawer) {
    showInstructionDrawer.value = false
  }
})
</script>

<template>
  <div class="edit-page-layout bug-report-edit-root">
    <!-- Main form area -->
    <div class="edit-main">
      <el-card shadow="never" v-loading="loading" class="edit-card">
        <template #header>
          <div class="header" :class="{ 'header--mobile': isMobileNarrow }">
            <div class="title-group">
              <div v-if="isEditMode" class="status-line">
                <span>当前状态：</span>
                <el-tag :type="getBugReportStatusTagType(currentStatus)">
                  {{ getBugReportStatusLabel(currentStatus) }}
                </el-tag>
              </div>
            </div>
            <template v-if="!isMobileNarrow">
              <el-space wrap>
                <el-button @click="handleCancel">取消</el-button>
                <el-button
                  v-if="useInstructionDrawer"
                  type="info"
                  plain
                  @click="showInstructionDrawer = true"
                >
                  <el-icon class="btn-icon"><InfoFilled /></el-icon>
                  填写说明
                </el-button>
                <el-button type="info" plain @click="showMobilePreview = true">
                  <el-icon class="btn-icon"><Monitor /></el-icon>
                  手机预览
                </el-button>
                <el-button type="success" plain @click="handleCopyContent">
                  <el-icon class="btn-icon"><DocumentCopy /></el-icon>
                  一键复制
                </el-button>
                <el-button
                  v-if="canEdit"
                  type="primary"
                  plain
                  :loading="submitLoading"
                  @click="handleSaveDraft"
                >
                  保存草稿
                </el-button>
                <el-button
                  v-if="canEdit"
                  type="primary"
                  :loading="submitLoading"
                  @click="handleSaveAndSubmit"
                >
                  保存并提交
                </el-button>
              </el-space>
            </template>
            <div v-else class="mobile-toolbar">
              <el-button size="small" @click="handleCancel">取消</el-button>
              <el-button
                v-if="useInstructionDrawer"
                size="small"
                type="default"
                @click="showInstructionDrawer = true"
              >
                说明
              </el-button>
              <el-dropdown trigger="click" @command="handleMobileToolbarCommand">
                <el-button size="small" type="primary" plain>
                  更多
                  <el-icon class="btn-icon btn-icon--after"><ArrowDown /></el-icon>
                </el-button>
                <template #dropdown>
                  <el-dropdown-menu>
                    <el-dropdown-item command="preview">
                      <el-icon class="dropdown-item-icon"><Monitor /></el-icon>
                      手机预览
                    </el-dropdown-item>
                    <el-dropdown-item command="copy">
                      <el-icon class="dropdown-item-icon"><DocumentCopy /></el-icon>
                      一键复制
                    </el-dropdown-item>
                  </el-dropdown-menu>
                </template>
              </el-dropdown>
              <el-button
                v-if="canEdit"
                size="small"
                type="primary"
                plain
                :loading="submitLoading"
                @click="handleSaveDraft"
              >
                草稿
              </el-button>
              <el-button
                v-if="canEdit"
                size="small"
                type="primary"
                :loading="submitLoading"
                @click="handleSaveAndSubmit"
              >
                提交
              </el-button>
            </div>
          </div>
        </template>

        <el-alert
          v-if="!canEdit"
          title="当前简报状态不可编辑，请返回详情页处理流程操作。"
          type="warning"
          :closable="false"
          show-icon
          class="status-alert"
        />

        <el-form
          :label-width="isMobileNarrow ? 'auto' : '120px'"
          :label-position="isMobileNarrow ? 'top' : 'right'"
          :disabled="!canEdit"
          class="edit-form"
          :class="{ 'edit-form--mobile-stack': isMobileNarrow }"
        >
          <!-- Common fields -->
          <el-form-item label="关联工单" required>
            <div class="ticket-select-wrap">
              <el-select
                v-model="form.ticketIds"
                multiple
                filterable
                remote
                reserve-keyword
                collapse-tags
                collapse-tags-tooltip
                class="w-640"
                :loading="ticketLoading"
                placeholder="输入工单编号或标题搜索"
                :remote-method="handleTicketRemoteSearch"
              >
                <el-option
                  v-for="option in ticketOptions"
                  :key="option.value"
                  :label="option.label"
                  :value="option.value"
                />
              </el-select>
              <div class="prefill-hint">
                <span v-if="prefillLoading" class="prefill-hint--loading">正在自动填充相关字段…</span>
                <span v-else-if="form.ticketIds.length > 0">已根据关联工单自动预填部分字段，可手动修改</span>
                <span v-else>选择工单后将自动预填问题描述及相关字段</span>
              </div>
            </div>
          </el-form-item>

          <el-form-item label="问题描述" required>
            <el-input
              v-model="form.problemDesc"
              type="textarea"
              :autosize="{ minRows: isMobileNarrow ? 5 : 4, maxRows: isMobileNarrow ? 22 : 16 }"
              maxlength="1000"
              show-word-limit
              placeholder="请输入问题描述"
              class="textarea-autosize"
            />
          </el-form-item>

          <el-form-item label="逻辑归因">
            <el-select
              v-model="selectedLogicCause"
              clearable
              filterable
              class="w-520"
              placeholder="请选择逻辑归因（可选）"
            >
              <el-option
                v-for="item in logicCauseOptions"
                :key="item.value"
                :label="item.label"
                :value="item.value"
              />
            </el-select>
          </el-form-item>

          <el-form-item label="归因明细">
            <el-input
              v-model="form.logicCauseDetail"
              type="textarea"
              :autosize="{ minRows: isMobileNarrow ? 3 : 2, maxRows: isMobileNarrow ? 14 : 12 }"
              maxlength="500"
              show-word-limit
              placeholder="请输入归因补充说明（可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <el-form-item label="缺陷分类" required>
            <el-select
              v-model="form.defectCategory"
              clearable
              filterable
              class="w-420"
              placeholder="请选择缺陷分类"
            >
              <el-option
                v-for="item in defectCategories"
                :key="item.id"
                :label="item.name"
                :value="item.name"
              />
            </el-select>
          </el-form-item>

          <el-form-item label="引入项目">
            <el-input
              v-model="form.introducedProject"
              maxlength="100"
              show-word-limit
              placeholder="请输入引入项目（可选）"
              class="w-420"
            />
          </el-form-item>

          <el-form-item label="开始时间">
            <el-date-picker
              v-model="form.startDate"
              type="date"
              value-format="YYYY-MM-DD"
              placeholder="请选择开始日期（可选）"
            />
          </el-form-item>

          <el-form-item label="严重级别">
            <div class="severity-wrap">
              <el-select
                v-model="form.severityLevel"
                class="severity-select"
                placeholder="请选择"
              >
                <el-option
                  v-for="level in SEVERITY_LEVELS"
                  :key="level.value"
                  :label="level.label"
                  :value="level.value"
                />
              </el-select>
              <el-button
                v-if="isMobileNarrow"
                type="primary"
                link
                class="severity-toggle"
                @click="showSeverityDescriptions = !showSeverityDescriptions"
              >
                {{ showSeverityDescriptions ? '收起级别说明' : '查看各级别说明' }}
              </el-button>
              <div v-if="!isMobileNarrow || showSeverityDescriptions" class="severity-desc-list">
                <div
                  v-for="level in SEVERITY_LEVELS"
                  :key="level.value"
                  class="severity-desc-item"
                  :class="[`severity-desc-item--${level.value.toLowerCase()}`, { 'is-active': form.severityLevel === level.value }]"
                >
                  <span class="severity-tag">{{ level.label }}</span>
                  <span class="severity-desc-text">{{ level.desc }}</span>
                </div>
              </div>
            </div>
          </el-form-item>

          <el-collapse
            v-if="isMobileNarrow"
            v-model="advancedCollapseActive"
            class="advanced-fields-collapse"
          >
            <el-collapse-item title="更多字段（选填）" name="more">
              <template #title>
                <span class="collapse-title-text">更多字段（选填）</span>
                <span class="collapse-title-hint">影响范围、解决方案、审核人等</span>
              </template>

          <el-form-item label="影响范围">
            <el-input
              v-model="form.impactScope"
              type="textarea"
              :autosize="{ minRows: 3, maxRows: 14 }"
              maxlength="500"
              show-word-limit
              placeholder="请输入影响范围（可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <!-- Solution fields - flat layout per PRD F2.1 -->
          <el-form-item label="临时解决时间">
            <el-date-picker
              v-model="form.tempResolveDate"
              type="date"
              value-format="YYYY-MM-DD"
              placeholder="请选择临时解决日期（可选）"
            />
          </el-form-item>

          <el-form-item label="临时解决方案">
            <el-input
              v-model="form.tempSolution"
              type="textarea"
              :autosize="{ minRows: 4, maxRows: 18 }"
              maxlength="1000"
              show-word-limit
              placeholder="请输入临时解决方案（权宜之计，可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <el-form-item label="彻底解决日期">
            <el-date-picker
              v-model="form.resolveDate"
              type="date"
              value-format="YYYY-MM-DD"
              placeholder="请选择彻底解决日期（可选）"
            />
          </el-form-item>

          <el-form-item label="彻底解决方案">
            <el-input
              v-model="form.solution"
              type="textarea"
              :autosize="{ minRows: 5, maxRows: 22 }"
              maxlength="1000"
              show-word-limit
              placeholder="请输入彻底解决方案（根本性修复，可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <el-form-item label="反馈人">
            <el-select
              v-model="form.reporterId"
              clearable
              filterable
              class="w-420"
              placeholder="请选择反馈人（可选）"
            >
              <el-option v-for="user in users" :key="user.id" :label="user.name" :value="user.id" />
            </el-select>
          </el-form-item>

          <el-form-item label="审核人">
            <el-select
              v-model="form.reviewerId"
              clearable
              filterable
              class="w-420"
              placeholder="请选择审核人"
            >
              <el-option v-for="user in users" :key="user.id" :label="user.name" :value="user.id" />
            </el-select>
          </el-form-item>

          <el-form-item label="责任人">
            <el-select
              v-model="form.responsibleUserIds"
              multiple
              clearable
              filterable
              class="w-520"
              placeholder="请选择责任人（可多选）"
            >
              <el-option v-for="user in users" :key="user.id" :label="user.name" :value="user.id" />
            </el-select>
          </el-form-item>

          <el-form-item label="备注">
            <el-input
              v-model="form.remark"
              type="textarea"
              :autosize="{ minRows: isMobileNarrow ? 4 : 3, maxRows: isMobileNarrow ? 16 : 12 }"
              maxlength="500"
              show-word-limit
              placeholder="请输入备注（可选）"
              class="textarea-autosize"
            />
          </el-form-item>
            </el-collapse-item>
          </el-collapse>

          <template v-if="!isMobileNarrow">
          <el-form-item label="影响范围">
            <el-input
              v-model="form.impactScope"
              type="textarea"
              :autosize="{ minRows: 2, maxRows: 12 }"
              maxlength="500"
              show-word-limit
              placeholder="请输入影响范围（可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <!-- Solution fields - flat layout per PRD F2.1 -->
          <el-form-item label="临时解决时间">
            <el-date-picker
              v-model="form.tempResolveDate"
              type="date"
              value-format="YYYY-MM-DD"
              placeholder="请选择临时解决日期（可选）"
            />
          </el-form-item>

          <el-form-item label="临时解决方案">
            <el-input
              v-model="form.tempSolution"
              type="textarea"
              :autosize="{ minRows: 3, maxRows: 14 }"
              maxlength="1000"
              show-word-limit
              placeholder="请输入临时解决方案（权宜之计，可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <el-form-item label="彻底解决日期">
            <el-date-picker
              v-model="form.resolveDate"
              type="date"
              value-format="YYYY-MM-DD"
              placeholder="请选择彻底解决日期（可选）"
            />
          </el-form-item>

          <el-form-item label="彻底解决方案">
            <el-input
              v-model="form.solution"
              type="textarea"
              :autosize="{ minRows: 4, maxRows: 16 }"
              maxlength="1000"
              show-word-limit
              placeholder="请输入彻底解决方案（根本性修复，可选）"
              class="textarea-autosize"
            />
          </el-form-item>

          <el-form-item label="反馈人">
            <el-select
              v-model="form.reporterId"
              clearable
              filterable
              class="w-420"
              placeholder="请选择反馈人（可选）"
            >
              <el-option v-for="user in users" :key="user.id" :label="user.name" :value="user.id" />
            </el-select>
          </el-form-item>

          <el-form-item label="审核人">
            <el-select
              v-model="form.reviewerId"
              clearable
              filterable
              class="w-420"
              placeholder="请选择审核人"
            >
              <el-option v-for="user in users" :key="user.id" :label="user.name" :value="user.id" />
            </el-select>
          </el-form-item>

          <el-form-item label="责任人">
            <el-select
              v-model="form.responsibleUserIds"
              multiple
              clearable
              filterable
              class="w-520"
              placeholder="请选择责任人（可多选）"
            >
              <el-option v-for="user in users" :key="user.id" :label="user.name" :value="user.id" />
            </el-select>
          </el-form-item>

          <el-form-item label="备注">
            <el-input
              v-model="form.remark"
              type="textarea"
              :autosize="{ minRows: 3, maxRows: 12 }"
              maxlength="500"
              show-word-limit
              placeholder="请输入备注（可选）"
              class="textarea-autosize"
            />
          </el-form-item>
          </template>
        </el-form>
      </el-card>
    </div>

    <div v-show="!useInstructionDrawer" class="edit-sidebar">
      <el-card shadow="never" class="instruction-card">
        <template #header>
          <div class="instruction-header">
            <el-icon class="instruction-icon"><InfoFilled /></el-icon>
            <span>填写说明</span>
          </div>
        </template>

        <BugReportInstructionContent layout="sidebar" :defect-categories="defectCategories" />
      </el-card>
    </div>
  </div>

  <el-drawer
    v-model="showInstructionDrawer"
    title="填写说明"
    direction="btt"
    size="88%"
    append-to-body
    class="bug-report-instruction-drawer"
  >
    <BugReportInstructionContent layout="drawer" :defect-categories="defectCategories" />
  </el-drawer>

  <!-- Mobile preview modal -->
  <el-dialog
    v-model="showMobilePreview"
    title="手机预览"
    width="400px"
    :close-on-click-modal="true"
    class="mobile-preview-dialog"
  >
    <div class="mobile-phone-frame">
      <div class="phone-notch"></div>
      <div class="phone-screen">
        <div class="phone-screen-header">
          <span class="phone-screen-title">Bug简报</span>
        </div>
        <div class="phone-screen-body">
          <div class="phone-content">
            <div v-if="form.problemDesc" class="phone-field">
              <div class="phone-field-label">问题描述</div>
              <div class="phone-field-value">{{ form.problemDesc }}</div>
            </div>
            <div v-if="form.logicCausePath[0]" class="phone-field">
              <div class="phone-field-label">逻辑归因</div>
              <div class="phone-field-value">{{ form.logicCausePath[0] }}</div>
            </div>
            <div v-if="form.logicCauseDetail" class="phone-field">
              <div class="phone-field-label">归因明细</div>
              <div class="phone-field-value">{{ form.logicCauseDetail }}</div>
            </div>
            <div v-if="form.defectCategory" class="phone-field">
              <div class="phone-field-label">缺陷分类</div>
              <div class="phone-field-value">{{ form.defectCategory }}</div>
            </div>
            <div v-if="form.introducedProject" class="phone-field">
              <div class="phone-field-label">引入项目</div>
              <div class="phone-field-value">{{ form.introducedProject }}</div>
            </div>
            <div v-if="form.startDate" class="phone-field">
              <div class="phone-field-label">开始时间</div>
              <div class="phone-field-value">{{ form.startDate }}</div>
            </div>
            <div v-if="form.severityLevel" class="phone-field">
              <div class="phone-field-label">严重级别</div>
              <div class="phone-field-value">
                <span :class="`severity-badge severity-badge--${form.severityLevel.toLowerCase()}`">
                  {{ form.severityLevel }}
                </span>
              </div>
            </div>
            <div v-if="form.impactScope" class="phone-field">
              <div class="phone-field-label">影响范围</div>
              <div class="phone-field-value">{{ form.impactScope }}</div>
            </div>
            <div v-if="form.tempResolveDate" class="phone-field">
              <div class="phone-field-label">临时解决时间</div>
              <div class="phone-field-value">{{ form.tempResolveDate }}</div>
            </div>
            <div v-if="form.tempSolution" class="phone-field">
              <div class="phone-field-label">临时解决方案</div>
              <div class="phone-field-value">{{ form.tempSolution }}</div>
            </div>
            <div v-if="form.resolveDate" class="phone-field">
              <div class="phone-field-label">彻底解决时间</div>
              <div class="phone-field-value">{{ form.resolveDate }}</div>
            </div>
            <div v-if="form.solution" class="phone-field">
              <div class="phone-field-label">彻底解决方案</div>
              <div class="phone-field-value">{{ form.solution }}</div>
            </div>
            <div v-if="form.remark" class="phone-field">
              <div class="phone-field-label">备注</div>
              <div class="phone-field-value">{{ form.remark }}</div>
            </div>
            <div v-if="!form.problemDesc && !form.defectCategory" class="phone-empty">
              暂无内容，请先填写表单
            </div>
          </div>
        </div>
      </div>
      <div class="phone-home-bar"></div>
    </div>
    <template #footer>
      <el-button type="primary" @click="handleCopyContent">
        <el-icon><DocumentCopy /></el-icon>
        一键复制
      </el-button>
      <el-button @click="showMobilePreview = false">关闭</el-button>
    </template>
  </el-dialog>
</template>

<style scoped lang="scss">
.bug-report-edit-root {
  padding-bottom: max(24px, env(safe-area-inset-bottom, 0px));
  /* 表单项内容区占满主栏宽度，避免固定 px 宽度在「侧栏 + 中等视口」下右侧大块留白 */
  .edit-form {
    :deep(.el-form-item__content) {
      width: 100%;
      max-width: 100%;
    }

    :deep(.el-select),
    :deep(.el-cascader),
    :deep(.el-date-editor.el-input),
    :deep(.el-date-editor.el-input__wrapper) {
      width: 100% !important;
      max-width: 100%;
    }

    :deep(.el-input:not(.el-input--textarea)) {
      width: 100%;
      max-width: 100%;
    }
  }

  .w-220,
  .w-420,
  .w-520,
  .w-640 {
    width: 100%;
    max-width: 100%;
  }
}

.edit-card {
  :deep(.el-card__header) {
    border-bottom: 1px solid var(--el-border-color-lighter, #ebeef5);
  }

  :deep(.el-card__body) {
    @media (max-width: 768px) {
      padding: 16px 14px 20px;
    }
  }
}

.header--mobile {
  flex-direction: column;
  align-items: stretch;
  gap: 10px;
}

.mobile-toolbar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px;
}

.btn-icon--after {
  margin-left: 2px;
  margin-right: 0;
  vertical-align: middle;
}

.dropdown-item-icon {
  margin-right: 6px;
  vertical-align: middle;
}

.edit-form--mobile-stack {
  :deep(.el-form-item) {
    margin-bottom: 22px;
  }

  :deep(.el-form-item__label) {
    font-weight: 500;
    color: #303133;
    padding-bottom: 6px;
    line-height: 1.45;
  }

  :deep(.el-date-editor.el-input),
  :deep(.el-date-editor.el-input__wrapper) {
    width: 100%;
    max-width: 100%;
  }
}

.textarea-autosize {
  width: 100%;

  :deep(.el-textarea__inner) {
    line-height: 1.55;
    min-height: 0;
  }
}

.bug-report-instruction-drawer {
  :deep(.el-drawer__body) {
    padding: 0 12px max(16px, env(safe-area-inset-bottom, 0px));
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
  }
}

.severity-select {
  width: 100%;
  max-width: 100%;
}

.severity-toggle {
  margin-top: 4px;
  padding-left: 0;
  font-size: 13px;
}

.advanced-fields-collapse {
  margin-top: 4px;
  margin-bottom: 8px;
  border: none;

  :deep(.el-collapse-item__header) {
    height: auto;
    min-height: 44px;
    line-height: 1.35;
    padding: 10px 12px;
    border-radius: 10px;
    background: #f8fafc;
    border: 1px solid #eef2f7;
    font-weight: 600;
    color: #303133;
    transition: background var(--md-transition-fast, 0.15s ease);
  }

  :deep(.el-collapse-item__header:hover) {
    background: #f0f6ff;
  }

  :deep(.el-collapse-item__wrap) {
    border-bottom: none;
  }

  :deep(.el-collapse-item__content) {
    padding: 12px 0 4px;
  }
}

.collapse-title-text {
  display: block;
}

.collapse-title-hint {
  display: block;
  font-size: 12px;
  font-weight: 400;
  color: #909399;
  margin-top: 2px;
}

.edit-page-layout {
  display: flex;
  gap: 16px;
  align-items: flex-start;
}

.edit-main {
  flex: 1;
  min-width: 0;
}

.edit-sidebar {
  width: 320px;
  flex-shrink: 0;
  position: sticky;
  top: 16px;
  max-height: calc(100vh - 80px);
  overflow-y: auto;

  &::-webkit-scrollbar {
    width: 4px;
  }
  &::-webkit-scrollbar-thumb {
    background: #dcdfe6;
    border-radius: 2px;
  }
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 12px;
  flex-wrap: wrap;
}

.title-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.status-line {
  color: #606266;
  font-size: 13px;
  display: flex;
  align-items: center;
  gap: 8px;
}

.status-alert {
  margin-bottom: 16px;
}

.edit-form {
  max-width: 100%;
}

.ticket-select-wrap {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.severity-wrap {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.severity-desc-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
  max-width: 640px;
}

.severity-desc-item {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 5px 8px;
  border-radius: 4px;
  font-size: 12px;
  background: #f8f9fa;
  transition: background 0.15s;

  &.is-active {
    background: #ecf5ff;
    outline: 1px solid #b3d8ff;
  }
}

.severity-tag {
  flex-shrink: 0;
  font-weight: 600;
  min-width: 72px;
}

.severity-desc-text {
  color: #606266;
  line-height: 1.5;
}

.severity-desc-item--p0 .severity-tag { color: #f56c6c; }
.severity-desc-item--p1 .severity-tag { color: #e6a23c; }
.severity-desc-item--p2 .severity-tag { color: #409eff; }
.severity-desc-item--p3 .severity-tag { color: #67c23a; }
.severity-desc-item--p4 .severity-tag { color: #909399; }

.prefill-hint {
  display: flex;
  align-items: center;
  gap: 4px;
  color: #909399;
  font-size: 12px;

  &--loading {
    color: #1675d1;
  }
}

.btn-icon {
  margin-right: 4px;
}

.w-220 {
  width: 220px;
}

.w-420 {
  width: 420px;
}

.w-520 {
  width: 520px;
}

.w-640 {
  width: 640px;
}

// Instruction card styles
.instruction-card {
  :deep(.el-card__header) {
    padding: 12px 16px;
    background: #f0f6ff;
    border-bottom: 1px solid #d9ecff;
  }

  :deep(.el-card__body) {
    padding: 0;
  }
}

.instruction-header {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  font-weight: 600;
  color: #1675d1;
}

.instruction-icon {
  font-size: 16px;
}

// Mobile preview dialog
.mobile-preview-dialog {
  :deep(.el-dialog__body) {
    display: flex;
    justify-content: center;
    padding: 20px;
    background: #f0f2f5;
  }
}

.mobile-phone-frame {
  width: 320px;
  background: #1a1a1a;
  border-radius: 40px;
  padding: 12px 8px 8px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0;
}

.phone-notch {
  width: 100px;
  height: 24px;
  background: #1a1a1a;
  border-radius: 0 0 16px 16px;
  margin-bottom: 4px;
  position: relative;
  z-index: 1;

  &::after {
    content: '';
    position: absolute;
    top: 6px;
    left: 50%;
    transform: translateX(-50%);
    width: 60px;
    height: 12px;
    background: #2a2a2a;
    border-radius: 8px;
  }
}

.phone-screen {
  width: 100%;
  background: #fff;
  border-radius: 20px;
  overflow: hidden;
  min-height: 480px;
  max-height: 520px;
  display: flex;
  flex-direction: column;
}

.phone-screen-header {
  background: #1675d1;
  padding: 12px 16px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.phone-screen-title {
  color: #fff;
  font-size: 14px;
  font-weight: 600;
}

.phone-screen-body {
  flex: 1;
  overflow-y: auto;
  padding: 12px;

  &::-webkit-scrollbar {
    width: 3px;
  }
  &::-webkit-scrollbar-thumb {
    background: #dcdfe6;
    border-radius: 2px;
  }
}

.phone-content {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.phone-field {
  border-bottom: 1px solid #f0f0f0;
  padding-bottom: 8px;
}

.phone-field-label {
  font-size: 11px;
  color: #909399;
  margin-bottom: 3px;
}

.phone-field-value {
  font-size: 13px;
  color: #303133;
  line-height: 1.5;
  word-break: break-word;
}

.phone-empty {
  text-align: center;
  color: #c0c4cc;
  font-size: 13px;
  padding: 40px 0;
}

.phone-home-bar {
  width: 100px;
  height: 4px;
  background: #4a4a4a;
  border-radius: 2px;
  margin-top: 8px;
}

.severity-badge {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 3px;
  font-size: 12px;
  font-weight: 600;

  &--p0 {
    background: #fef0f0;
    color: #f56c6c;
  }
  &--p1 {
    background: #fdf6ec;
    color: #e6a23c;
  }
  &--p2 {
    background: #ecf5ff;
    color: #409eff;
  }
  &--p3 {
    background: #f0f9eb;
    color: #67c23a;
  }
  &--p4 {
    background: #f4f4f5;
    color: #909399;
  }
}

@media (max-width: 1200px) {
  .edit-sidebar {
    width: 280px;
  }
}

@media (max-width: 991px) {
  .edit-page-layout {
    flex-direction: column;
  }

  .edit-sidebar {
    width: 100%;
    position: static;
    max-height: none;
  }

  .header:not(.header--mobile) {
    flex-direction: column;
    align-items: flex-start;
  }

  .w-220,
  .w-420,
  .w-520,
  .w-640 {
    width: 100%;
  }
}

@media (max-width: 768px) {
  .edit-page-layout {
    gap: 12px;
  }

  .severity-desc-list {
    max-width: none;
  }

  .severity-desc-item {
    padding: 10px 12px;
    border-radius: 8px;
  }
}
</style>
